version: '3'
services:
  airflow-webserver:
    image: apache/airflow:2.6.1
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    networks:
      - airflow-net
    ports:
      - "8080:8080"

  airflow-scheduler:
    image: apache/airflow:2.6.1
    networks:
      - airflow-net

  airflow-worker:
    image: apache/airflow:2.6.1
    networks:
      - airflow-net

  postgres:
    image: postgres:13
    networks:
      - airflow-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - airflow-net

networks:
  airflow-net:
    driver: bridge
